# Generated by Django 3.2.16 on 2022-10-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='status',
            field=models.CharField(choices=[('ac', 'active'), ('ex', 'expired')], default='ac', max_length=2),
        ),
    ]
