# Generated by Django 3.2.16 on 2022-11-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_insurance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='date_of_purchase',
            field=models.DateField(auto_now_add=True),
        ),
    ]
